language: node_js

before_install:
- npm install gitbook-cli -g
- gitbook install

install:

# Configure seu nome de usuário e e-mail
before_script:
- git config --global user.name 'Travis-ci'
- git config --global user.email 'josetelesmaciel@gmail.com'

script: bash ./deploy-to-gh-pages.sh

after_script:
- git push --force --quiet "$GH_REFERENCE" master:gh-pages